name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main # Change if you're using a different branch

permissions:
  contents: write # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # root folder
